### PR TITLE
Add the document for SmartSequenced

### PR DESCRIPTION
**Pull request by robario**

### CODE REVIEW

**Comment by gfx** [comment]
Thanks. Can please you add an example code?

**Comment by robario** [comment]
Sure, but. Since SYNOPSIS became too long, I thought that it is unnecessary. 
Also, SYNOPSIS does not cover all EXTENSIONS.
If you hope so, I'll add it to SYNOPSIS.

**Comment by robario** [comment]
I added an example into SYNOPSIS and benchmark script in addition.

**Comment by gfx** [comment]
Thanks! 寿司ゆき:thanks

**Pull request merged**
